# Generated by Django 5.2.5 on 2025-10-24 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DebtModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('debt_amount', models.FloatField(blank=True, default=0.0)),
                ('debt_name', models.CharField(blank=True, default='')),
                ('debt_payment', models.FloatField(blank=True, default=0)),
                ('debt_rate', models.CharField(blank=True, default='Weekly')),
                ('debt_interest', models.FloatField(blank=True, default=0)),
                ('debt_notes', models.CharField(blank=True, default='')),
                ('debt_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DebtModel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('expense_name', models.CharField(blank=True, default='', max_length=100)),
                ('expense_category', models.CharField(blank=True, default='Essential', max_length=100)),
                ('expense_amount', models.FloatField(blank=True, default=0, max_length=10)),
                ('expense_notes', models.CharField(blank=True, default='', max_length=200)),
                ('expense_rate', models.CharField(blank=True, default='Weekly', max_length=20)),
                ('expense_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customUserModel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('income_amount', models.FloatField(default=0)),
                ('income_name', models.CharField(blank=True, default='')),
                ('income_type', models.CharField(blank=True, default='')),
                ('income_rate', models.CharField(blank=True, default='Weekly')),
                ('income_notes', models.CharField(blank=True, default='')),
                ('income_datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserIncome', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BudgetModel',
        ),
    ]
