# Generated by Django 5.2.5 on 2025-10-30 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customuser_uuid_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InDebtModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative_debt', models.BooleanField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InDebtModel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
