# Generated by Django 5.2.5 on 2025-10-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_indebtmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='indebtmodel',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
