# Generated by Django 5.2.5 on 2025-10-31 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_indebtmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indebtmodel',
            name='username',
        ),
    ]
